(comment
  "Each new term in the Fibonacci sequence is generated by adding the previous
  two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  Find the sum of all the even-valued terms in the sequence which do not
  exceed four million.")

(ns com.typoet.euler.two
  (:gen-class))

; lazy sequence of fibonacci terms
(def fib-seq
  (lazy-cat [0 1] (map + (rest fib-seq) fib-seq)))

(def even-fib-seq
  (filter #(= 0 (rem % 2)) fib-seq))

(defn -main []
  (println
    (reduce + (take-while #(< % 4000000) even-fib-seq))))